version: "2"

services:
  web:
    build:
      context: web/.
      args:
        - OJS_URL_DOWNLOAD=true
        #- OJS_VCS_CLEANUP=false
        - OJS_URL_VERSION=2.4.5
        #- OJS_PATH=ojs
        #- OJS_GIT_URL=https://github.com/pkp/ojs.git
        #- OJS_GIT_TAG=ojs-2_4_7-1
        #-OJS_SVN_URL=http://svnurl
    links:
      # database is available in web under the hostnames "db" and "database"
      - "db:database"
    ports:
      - "80:80"
    volumes_from:
      - data
  db:
    image: mariadb:5
    ports:
      - "3306:3306"
    environment:
      # some configuration magic happening here, see https://github.com/docker-library/mysql/blob/master/5.7/docker-entrypoint.sh for details
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=ojs
      - MYSQL_PASSWORD=ojs
      - MYSQL_DATABASE=ojs
    volumes_from:
      - data
  data:
    build:
      context: data/.
